version: '3.8'

services:
  finaltest.api:
    image: ${DOCKER_REGISTRY-}finaltestapi
    build:
      context: .
      dockerfile: FinalTest.API/Dockerfile
    depends_on:
      - postgres_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=1488;Host=postgres_db;Port=5432;Database=BankSystemDb;
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  postgres_db:
     container_name: LiVBankSystemDb
     image: postgres:latest
     environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=1488
         - POSTGRES_DB=BankSystemDb
     ports:
         - "5432:5432"
     volumes:
         - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: